"""add_asset_registry

Revision ID: 0f2358fab959
Revises: 8e38beee69ff
Create Date: 2026-05-29 17:56:52.875245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2358fab959'
down_revision: Union[str, None] = '8e38beee69ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('cloud_provider', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('availability_zone', sa.String(), nullable=True),
    sa.Column('instance_name', sa.String(), nullable=True),
    sa.Column('vpc_name', sa.String(), nullable=True),
    sa.Column('vpc_id', sa.String(), nullable=True),
    sa.Column('private_ip_address', sa.String(), nullable=True),
    sa.Column('public_ip_address', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('team_verticals', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('engineering_dev_manager_email', sa.String(), nullable=True),
    sa.Column('engineering_dev_director_email', sa.String(), nullable=True),
    sa.Column('cloudops_manager_email', sa.String(), nullable=True),
    sa.Column('cloudops_director_email', sa.String(), nullable=True),
    sa.Column('power_state', sa.String(), nullable=True),
    sa.Column('os_details', sa.String(), nullable=True),
    sa.Column('os_distribution', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_registry_application'), 'asset_registry', ['application'], unique=False)
    op.create_index(op.f('ix_asset_registry_environment'), 'asset_registry', ['environment'], unique=False)
    op.create_index(op.f('ix_asset_registry_instance_name'), 'asset_registry', ['instance_name'], unique=False)
    op.create_index(op.f('ix_asset_registry_team'), 'asset_registry', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_registry_team'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_instance_name'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_environment'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_application'), table_name='asset_registry')
    op.drop_table('asset_registry')
    # ### end Alembic commands ###
